language: python

python:
  - "3.6.5"

before_install:
  - cd project/requirements

install:
  - pip install -r base.txt
  - python -c "import nltk; nltk.download('stopwords'); nltk.download('punkt')"

before_script:
  - cd ../..

script:
  - python manage.py test